# Generated by Django 5.0.3 on 2025-01-07 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbol', models.CharField(max_length=5)),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbol', models.CharField(max_length=5)),
                ('nama', models.CharField(max_length=50)),
                ('bobot', models.FloatField(default=0)),
                ('jenis', models.CharField(choices=[('BENEFIT', 'BENEFIT'), ('COST', 'COST')], default='benefit', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubKriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=3)),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subkriteria', to='businessloc_app.kriteria')),
            ],
        ),
    ]
