# Generated by Django 5.0.3 on 2025-01-08 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessloc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.ForeignKey(limit_choices_to={'kriteria__simbol': 'C1'}, on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_c1', to='businessloc_app.subkriteria')),
                ('c2', models.ForeignKey(limit_choices_to={'kriteria__simbol': 'C2'}, on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_c2', to='businessloc_app.subkriteria')),
                ('c3', models.ForeignKey(limit_choices_to={'kriteria__simbol': 'C3'}, on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_c3', to='businessloc_app.subkriteria')),
                ('c4', models.ForeignKey(limit_choices_to={'kriteria__simbol': 'C4'}, on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_c4', to='businessloc_app.subkriteria')),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_lokasi', to='businessloc_app.alternatif')),
            ],
        ),
    ]
