# Generated by Django 5.0.3 on 2025-01-08 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessloc_app', '0002_penilaian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penilaian',
            name='lokasi',
        ),
        migrations.AddField(
            model_name='penilaian',
            name='alternatif',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_al', to='businessloc_app.alternatif'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='penilaian',
            name='c1',
            field=models.ForeignKey(limit_choices_to={'kriteria__simbol': 'K1'}, on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_c1', to='businessloc_app.subkriteria'),
        ),
        migrations.AlterField(
            model_name='penilaian',
            name='c2',
            field=models.ForeignKey(limit_choices_to={'kriteria__simbol': 'K2'}, on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_c2', to='businessloc_app.subkriteria'),
        ),
        migrations.AlterField(
            model_name='penilaian',
            name='c3',
            field=models.ForeignKey(limit_choices_to={'kriteria__simbol': 'K3'}, on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_c3', to='businessloc_app.subkriteria'),
        ),
        migrations.AlterField(
            model_name='penilaian',
            name='c4',
            field=models.ForeignKey(limit_choices_to={'kriteria__simbol': 'K4'}, on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_c4', to='businessloc_app.subkriteria'),
        ),
    ]
